spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: order-service
          uri: http://order-service:8080
          predicates:
            - Path=/api/orders/**

        - id: menu-service
          uri: http://menu-service:8082
          predicates:
            - Path=/api/menu/**

        - id: inventory-service
          uri: http://inventory-service:8081
          predicates:
            - Path=/api/inventory/**

  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

server:
  port: 9000
